USE [master]
GO

/****** Object:  Database [MessageSenderDB]    Script Date: 23/1/2025 01:18:36 ******/
CREATE DATABASE [MessageSenderDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MessageSenderDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MessageSenderDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MessageSenderDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MessageSenderDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MessageSenderDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MessageSenderDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MessageSenderDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MessageSenderDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MessageSenderDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MessageSenderDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MessageSenderDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MessageSenderDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MessageSenderDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MessageSenderDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MessageSenderDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MessageSenderDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MessageSenderDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MessageSenderDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MessageSenderDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MessageSenderDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MessageSenderDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MessageSenderDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MessageSenderDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MessageSenderDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MessageSenderDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MessageSenderDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MessageSenderDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MessageSenderDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MessageSenderDB] SET  MULTI_USER 
GO

ALTER DATABASE [MessageSenderDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MessageSenderDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MessageSenderDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MessageSenderDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MessageSenderDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MessageSenderDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MessageSenderDB] SET  READ_WRITE 
GO


USE [MessageSenderDB]
GO
/****** Object:  Table [dbo].[CredentialsTwilio]    Script Date: 23/1/2025 01:17:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CredentialsTwilio](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SID] [varchar](100) NOT NULL,
	[Token] [varchar](100) NOT NULL,
	[FromNumber] [nchar](50) NOT NULL,
 CONSTRAINT [PK_CredentialsTwilio] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 23/1/2025 01:17:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PhoneNumber] [varchar](50) NOT NULL,
	[MessageBody] [varchar](500) NOT NULL,
	[Created] [datetime] NOT NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SentMessage]    Script Date: 23/1/2025 01:17:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SentMessage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MessageId] [int] NOT NULL,
	[SentDate] [datetime] NOT NULL,
	[CodeTwilio] [varchar](200) NOT NULL,
 CONSTRAINT [PK_SentMessage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CredentialsTwilio] ON 
GO
INSERT [dbo].[CredentialsTwilio] ([Id], [SID], [Token], [FromNumber]) VALUES (1, N'C', N'T', N'+1                                      ')
GO
SET IDENTITY_INSERT [dbo].[CredentialsTwilio] OFF
GO
SET IDENTITY_INSERT [dbo].[Message] ON 
GO
INSERT [dbo].[Message] ([Id], [PhoneNumber], [MessageBody], [Created]) VALUES (6, N'+50379432642', N'TEST1', CAST(N'2025-01-22T23:37:01.533' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Message] OFF
GO
SET IDENTITY_INSERT [dbo].[SentMessage] ON 
GO
INSERT [dbo].[SentMessage] ([Id], [MessageId], [SentDate], [CodeTwilio]) VALUES (2, 6, CAST(N'2025-01-22T23:37:11.243' AS DateTime), N'SMc4d74c1b85a8757fbc1427a35aec4eaa')
GO
SET IDENTITY_INSERT [dbo].[SentMessage] OFF
GO
ALTER TABLE [dbo].[Message] ADD  CONSTRAINT [DF_Message_Created]  DEFAULT (getdate()) FOR [Created]
GO
ALTER TABLE [dbo].[SentMessage] ADD  CONSTRAINT [DF_SentMessage_SentDate]  DEFAULT (getdate()) FOR [SentDate]
GO
